### ISSUE TITLE
issues stemming from comments preceding types

### ISSUE THREAD

**Issue by mmguero** [zeek/tree-sitter-zeek#9]
I've attached the following ZIP file containing two `.zeek` files that illustrate the issue I'm having. The scripts come from this [parser package](https://github.com/cisagov/icsnpp-opcua-binary/tree/main/scripts).

[sample-scripts.zip](https://github.com/zeek/zeekscript/files/10503428/sample-scripts.zip)

First, with `create-session-types.zeek` is the zeek script I'm parsing. the issue seems to be around these lines:

```
        #
        # Request
        #
        application_uri           : string  &log &optional;
        product_uri               : string  &log &optional;
```

When I run zeek-script format on the file, I see the following:

```
        #
    # Request
        #
        application_uri           : string  &log &optional;
        product_uri: string &log &optional;
```

You can't tell with the formatting here, probably, but the bare `#` by themselves are preceded by tabs, the `# Request` is preceded by spaces. I don't know if that has anything to do with it. The tab/spaces thing isn't coming from the original script file, where everything is spaces.

However, when I run `zeek-script` parse (or when I use the python module directly), I see this:

```
type_spec (18.8,18.49) 'opcua_link_id             : string  &log;'
    id (18.8,18.21) 'opcua_link_id'
    : (18.34,18.35) 
    type (18.36,18.42) 'string'
        string (18.36,18.42) 
    attr_list (18.44,18.48) '&log'
        attr (18.44,18.48) '&log'
            &log (18.44,18.48) 
    ; (18.48,18.49) 
type_spec (24.8,24.59) 'product_uri               : string  &log &optional;'
    id (24.8,24.19) 'product_uri'
    : (24.34,24.35) 
    type (24.36,24.42) 'string'
        string (24.36,24.42) 
    attr_list (24.44,24.58) '&log &optional'
        attr (24.44,24.48) '&log'
            &log (24.44,24.48) 
        attr (24.49,24.58) '&optional'
            &optional (24.49,24.58) 
```

You'll see that the `applicaiton_uri` field is missing. I thought maybe it had something to do with the `include_cst` parameter of my calls to traverse, but the output doesn't change whether it's True or False.

It definitely has to do with the comments on the lines before it, though. if I remove the comments before the parse, I don't lose that field.

Another (possibly related) problem that also deals with comments preceding things can be found with the other script (`variant-types.zeek`). The comments on these lines are causing the parse tree to fail, even though they are valid as far as I can tell.

```
#
# Note: The processing for a OpcUA_DataVariant that is itself of type OpcUA_DataVariant is to recursively call the
# data processing and link back into the OPCUA_Binary::VariantMetadata log file.
#
type OPCUA_Binary::VariantData: record {
```

the output ends like this:

```
        } (144.4,144.5) 
    stmt (144.5,144.6) ';'
        ; (144.5,144.6) 
    ERROR (145.0,145.1) [error] '}'
        } (145.0,145.1) 
parse tree has problems: cannot parse line 42, col 8: "ts                         : time    &log;
       [...]"
```

**Comment by ckreibich** [comment]
> I believe it was introduced originally to preserve line breaks in comments, but anything working on the CST should be able to reconstruct linebreaks if needed from source ranges. 

Yes, in order to figure out whether there's a newline between two tokens I could scan the raw content range — or just have the grammar tell me about them. I'm using this to guide formatting of comments around code, because it seemed cleaner that way — you can ask things like "is this preceded by a newline", "is this preceded by multiple newlines", etc, in tree node relationships, which is consistent with how a lot of my other tree traversal logic works.

I am sure it could be changed. I don't think it's super pressing because I think we already established that this grammar doesn't really work for your purposes.

**Comment by ckreibich** [comment]
Anyway! I tracked this down to a parsing problem about non-Zeekygen comments, which couldn't be empty (i.e. `#` immediately followed by a newline).
